name: Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -t my-node-app .
    - name: Push the Docker image to Docker Hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - run: docker tag my-node-app ${{ secrets.DOCKER_USERNAME }}/my-node-app
    - run: docker push ${{ secrets.DOCKER_USERNAME }}/my-node-app
    - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
            host: ${{ secrets.EC2_HOST }}
            username: ubuntu
            key: ${{ secrets.EC2_SSH_KEY }}
            script: |
                # Descargar la última imagen de Docker desde Docker Hub
                docker pull ${{ secrets.DOCKER_USERNAME }}/my-node-app
                # Detener y eliminar cualquier contenedor antiguo
                docker stop my-node-app || true
                docker rm my-node-app || true
                # Ejecutar un nuevo contenedor con la última imagen
                docker run -d -p 3000:3000 --name my-node-app ${{ secrets.DOCKER_USERNAME }}/my-node-app